name: minimal
channels:
  - conda-forge
dependencies:
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pip=19.3.1
  - python=3.8.0
  - readline=7.0
  - setuptools=42.0.2
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ffmpeg==1.4
    - ipykernel==5.1.3
    - ipython==7.10.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.3
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - notebook==6.0.2
    - numpy==1.17.4
    - pandocfilters==1.4.2
    - parso==0.5.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.2
    - ptyprocess==0.6.0
    - pygments==2.5.2
    - pyparsing==2.4.5
    - pyrsistent==0.15.6
    - python-dateutil==2.8.1
    - pyzmq==18.1.1
    - scipy==1.4.0
    - send2trash==1.5.0
    - six==1.13.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.3
    - traitlets==4.3.3
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1

