name: minimal
channels:
  - conda-forge
dependencies:
   - python=3.8.0
   - ffmpeg==1.4
   - ipykernel==5.1.3
   - ipython==7.10.2
   - ipython-genutils==0.2.0
   - ipywidgets==7.5.1
   - matplotlib==3.1.2
   - numpy==1.17.4
   - scipy==1.4.0
    

